### ISSUE TITLE
Lab3, Task 4 , error while running %run "./Includes/Classroom-Setup" in 02-ETL-Process-Overview(Python)

### ISSUE THREAD

**Issue by puneetsharma04** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#133] opened 2021-01-30 16:15 UTC
Error Description:
Notebook not found: Users/puneet.sharma04.in.ibm.com@hotmail.com/Includes/Classroom-Setup. Notebooks can be specified via a relative path (./Notebook or ../folder/Notebook) or via an absolute path (/Abs/Path/to/Notebook). Make sure you are specifying the path correctly.

Stacktrace:
  /Users/puneet.sharma04.in.ibm.com@hotmail.com/First_notebook: python

Please let me know how to resolve this.

**Comment by Kaijisse** [comment] 2021-02-12 09:49
Hi. 
I can't reproduce this error. 
Some things to keep in mind are, that the notebook is attached to a databricks cluster and that you're logging in with the same Azure Portal tenant as for the Databricks Cluster that is used in the same recourse group. 
Also please keep in mind:
- Within the Workspace, using the command bar on the left, select Workspace, Users, and select your username (the entry with house icon).
- In the blade that appears, select the downwards pointing chevron next to your name, and select Import.
- On the Import Notebooks dialog, select URL below and paste in the following URL: https://github.com/MicrosoftDocs/mslearn-perform-basic-data-transformation-in-azure-databricks/blob/master/DBC/05.1-Basic-ETL.dbc?raw=true

I'm now closing this issue.

**Closed** 2021-02-12 13:08 UTC

**Comment by puneetsharma04** [comment] 2021-02-12 13:14
I am able to make it work after Dettach & Attaching the cluster again.
