### ISSUE TITLE
Lab: Working with Relational Data Stores in the Cloud

### ISSUE THREAD

**Issue by Datachick** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#144] opened 2021-03-25 16:25 UTC
Exercise 1, Task 2

> _"Compute + storage: Click Configure database then in the page that appears click, Looking for basic, standard, premium?. Select Standard then click Apply."_

Students aren't easily finding the "Looking for basic, standard, premium" link.  I suggest a screenshot be added here to help them understand where they are supposed to click.

**Comment by Kaijisse** [comment] 2021-05-28 12:55
In lab 5: Working with Relational Data Stores in the Cloud, we no longer have a task 2 for Exercise 1, see screenshot. 
Therefore, I'm unable to reproduce this, and closing the issue. 
![image](https://user-images.githubusercontent.com/38757647/119986869-ac4aa380-bfc4-11eb-924c-23112d8d692f.png)

**Closed by Kaijisse** 2021-05-28 12:55 UTC
