### ISSUE TITLE
Exercise 2, task 3, step 2 typo

### ISSUE THREAD

**Issue by ArmandoLacerda** [MicrosoftLearning/DP-200-Implementing-an-Azure-Data-Solution#33] opened 2019-10-21 21:36 UTC
It says "blob", it should read "containers"

**Comment by vitaly-livshits** [comment] 2019-12-08 21:55
I think this is a duplicate of #31

**Comment by ctesta-oneillmsft** [comment] 2019-12-20 17:25
resolved

**Closed by ctesta-oneillmsft** 2019-12-20 17:25 UTC
